"""create table

Revision ID: f8abda8cb0e9
Revises: 
Create Date: 2023-09-25 12:42:10.441019

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8abda8cb0e9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer,

def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###

    with op.batch_alter_table("user") as alter_table_users_op:
        alter_table_users_op.add_column(
          sa.Column("username", sa.String()))
    accounts_table = table(
        "user",
        column("id", Integer),
        column("email", String),
        column("password", String),
        column('role_id',Integer),
        column("username", String),
      )
    op.bulk_insert(
        accounts_table,
        [
            {
               "id": 1,
                "email":"admin@gmail.com",
                "password":"34323",
                "role_id": 1,
                "username":"NEETU",
            },
        ],
    )
    ########################################################
    accounts_tables = table(
        "role",
        column("id", Integer),
        column("role_name", String),
      )
    op.bulk_insert(
        accounts_tables,
        [
            {
                "id": 1,
                "role_name": "ADMIN",
            },
            {
                "id": 2,
                "role_name": "MANAGER",
            },
            {
                "id": 3,
                "role_name": "USER",
            },
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
